# Generated by Django 3.1.5 on 2021-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blocks', '0002_auto_20210202_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
    ]
